version: "3"

services:
  db:
    image: "postgres"
    restart: "always"
    volumes:
      - ./.db-data:/var/lib/postgresql
      - ./docker/provision/postgres/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    networks:
      - net1
#  web:
#    build: .
#    image: "golang:1.6.1-alpine"
##    volumes:
##      - .:/var/www
##    command: ["go", "run", "./cmd/server/main.go"]
#    entrypoint: "go run cmd/server/main.go"
#    ports:
#      - "8088:8080"
#    depends_on:
#      - db
#    networks:
#      - net1
volumes:
  db-data:

networks:
  net1:
    driver: bridge
